# Generated by Django 6.0 on 2025-12-21 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('measurement_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('SUIT', 'Suit'), ('DRESS', 'Dress'), ('JACKET', 'Jacket'), ('CUSTOM', 'Custom')], max_length=20)),
                ('standard_measurements', models.JSONField(default=dict, help_text='Standard measurement fields for this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Measurement Template',
                'verbose_name_plural': 'Measurement Templates',
            },
        ),
        migrations.CreateModel(
            name='CustomerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements', models.JSONField(default=dict, help_text='Actual measurement values in key-value pairs')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_measurements', to='measurements.measurementtemplate')),
            ],
            options={
                'verbose_name': 'Customer Measurement',
                'verbose_name_plural': 'Customer Measurements',
                'ordering': ['-created_at'],
            },
        ),
    ]
